# Generated by Django 2.2.6 on 2019-10-31 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('date_published', models.DateTimeField(verbose_name='Дата ответа')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Author')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Article')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
