# Generated by Django 2.2.6 on 2019-11-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Число лайков'),
        ),
    ]
