# Generated by Django 2.2.6 on 2019-11-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_article_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='dislike',
            field=models.IntegerField(default=0, verbose_name='Число дизлайков'),
        ),
        migrations.AddField(
            model_name='answer',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Число лайков'),
        ),
    ]
