# Generated by Django 2.2.6 on 2019-11-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0005_auto_20191101_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_set', models.BooleanField(default=False, verbose_name='Число лайков')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='like',
        ),
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.ManyToManyField(to='question.Likes'),
        ),
    ]
