# Generated by Django 2.2.6 on 2019-11-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0006_auto_20191101_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like',
        ),
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Число лайков'),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
