# Generated by Django 2.2.6 on 2019-11-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0007_auto_20191101_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TechnoPark', max_length=255, verbose_name='Тег')),
                ('count', models.IntegerField(verbose_name='Число упоминаний')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='question.Tags'),
        ),
    ]
