# Generated by Django 2.2.6 on 2019-11-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0008_auto_20191101_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='admin', max_length=255, verbose_name='Автор лайка')),
                ('is_set', models.BooleanField(default=False, verbose_name='Поставлен ли лайк')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='admin', max_length=255, verbose_name='Автор лайка')),
                ('is_set', models.BooleanField(default=False, verbose_name='Поставлен ли лайк')),
            ],
        ),
    ]
