# Generated by Django 2.2.6 on 2019-11-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0010_auto_20191102_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='dislike',
        ),
        migrations.AddField(
            model_name='answer',
            name='dislike',
            field=models.ManyToManyField(to='question.Dislike'),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='like',
        ),
        migrations.AddField(
            model_name='answer',
            name='like',
            field=models.ManyToManyField(to='question.Like'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='dislike',
        ),
        migrations.AddField(
            model_name='article',
            name='dislike',
            field=models.ManyToManyField(to='question.Dislike'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='like',
        ),
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.ManyToManyField(to='question.Like'),
        ),
    ]
