# Generated by Django 2.2.6 on 2019-11-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0011_auto_20191102_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='like',
            field=models.ManyToManyField(related_name='Like', to='question.Like'),
        ),
    ]
