# Generated by Django 2.2.6 on 2019-11-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_auto_20191102_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='dislike',
            field=models.ManyToManyField(blank=True, to='question.Dislike'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='like',
            field=models.ManyToManyField(blank=True, to='question.Like'),
        ),
        migrations.AlterField(
            model_name='article',
            name='dislike',
            field=models.ManyToManyField(blank=True, to='question.Dislike'),
        ),
        migrations.AlterField(
            model_name='article',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='Like', to='question.Like'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='question.Tags'),
        ),
    ]
