# Generated by Django 2.2.6 on 2019-11-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0014_auto_20191124_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, verbose_name='Опубликовано'),
        ),
    ]
