# Generated by Django 2.2.6 on 2019-11-25 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0015_auto_20191125_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 8, 56, 13, 400841),
                                       verbose_name='Дата публикации'),
        ),
    ]
