# Generated by Django 2.2.6 on 2019-11-25 10:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0017_auto_20191125_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='birthday',
        ),
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 10, 3, 22, 144408, tzinfo=utc),
                                       verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Число упоминаний'),
        ),
    ]
