# Generated by Django 2.2.6 on 2019-11-27 12:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0020_auto_20191125_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 12, 21, 55, 91647),
                                       verbose_name='Дата ответа'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 12, 21, 55, 89369, tzinfo=utc),
                                       verbose_name='Дата публикации'),
        ),
    ]
