# Generated by Django 3.0 on 2019-12-03 15:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0022_auto_20191127_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 15, 15, 3, 807433, tzinfo=utc),
                                       verbose_name='Дата ответа'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 15, 15, 3, 804546, tzinfo=utc),
                                       verbose_name='Дата публикации'),
        ),
    ]
