# Generated by Django 3.0 on 2019-12-10 13:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0025_auto_20191210_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 13, 28, 36, 305659, tzinfo=utc),
                                       verbose_name='Дата ответа'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 13, 28, 36, 303393, tzinfo=utc),
                                       verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='question.Author'),
        ),
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='question.Author'),
        ),
    ]
