# Generated by Django 3.0 on 2019-12-10 13:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0026_auto_20191210_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 13, 30, 33, 715766, tzinfo=utc),
                                       verbose_name='Дата ответа'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 13, 30, 33, 707060, tzinfo=utc),
                                       verbose_name='Дата публикации'),
        ),
    ]
