# Generated by Django 3.0 on 2019-12-10 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0027_auto_20191210_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 13, 32, 16, 838380, tzinfo=utc),
                                       verbose_name='Дата ответа'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 13, 32, 16, 835382, tzinfo=utc),
                                       verbose_name='Дата публикации'),
        ),
    ]
