# Generated by Django 3.0 on 2019-12-15 20:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('question', '0032_auto_20191210_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='is_set',
        ),
        migrations.RemoveField(
            model_name='like',
            name='is_set',
        ),
        migrations.AlterField(
            model_name='answer',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 15, 20, 41, 0, 225666, tzinfo=utc),
                                       verbose_name='Дата ответа'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(db_index=True,
                                       default=datetime.datetime(2019, 12, 15, 20, 41, 0, 222617, tzinfo=utc),
                                       verbose_name='Дата публикации'),
        ),
    ]
