# Generated by Django 3.0 on 2019-12-15 20:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('userprofile', '0002_auto_20191203_1815'),
        ('question', '0033_auto_20191215_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 15, 20, 52, 16, 964470, tzinfo=utc),
                                       verbose_name='Дата ответа'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(db_index=True,
                                       default=datetime.datetime(2019, 12, 15, 20, 52, 16, 962142, tzinfo=utc),
                                       verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='dislike',
            field=models.ManyToManyField(blank=True, to='userprofile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='article',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='Like', to='userprofile.UserProfile'),
        ),
    ]
