# Generated by Django 3.0 on 2019-12-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='question/static/question/base/default.jpeg', upload_to='images/users',
                                    verbose_name='Изображение'),
        ),
    ]
